server:
  port: 8089
spring:
  application:
    name: middleware-redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    username: root
    password: 123456Aa
    url: jdbc:mysql://localhost:3316/cloudDB01
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
  redis:
    host: localhost
    port: 6379
    password: 123456Aa
logging:
  #  pattern:
  #    console: '%d -%msg%n'
  path: /Users/yuan/idea/mnt/smf/${spring.application.name}/logs
  level:
    root: info