server:
  port: 8099

spring:
  application:
    name: middleware-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    username: root
    password: 123456Aa
    url: jdbc:mysql://localhost:3316/cloudDB01
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
  redis:
    host: localhost
    port: 6379
    password: 123456Aa
    #标准的JDK 基于接口的代理将起作用
  aop:
    proxy-target-class: false

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    #输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
    cacheEnabled: false

idworder:
  worker-id: ${random.int[1,31]}
  datacenter-id: ${random.int[1,31]}